POST http://127.0.0.1:3003/api/blogs 
content-type: application/json

{
    "title": "test",
    "author": "Ben",
    "url": "test1s",
    "userId":"639c37998560aef432ebe685",
    "likes": 0
}

GET http://127.0.0.1:3003/api/blogs
